---
title: "UCD Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{UCD}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---
  
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>")
```

```{r setup, include = FALSE}
library(WONDER)    # devtools::install_github("BAAQMD/WONDER")
library(ggtools)   # devtools::install_github("BAAQMD/ggtools")
library(exptools)  # devtools::install_github("BAAQMD/exptools")
```

```{r extdata_path}
extdata_path <- function (...) {
  system.file("extdata", ..., package = "WONDER")
}
```

```{r SFBA_UCD_metadata}
SFBA_UCD_metadata <-
  crossing(
    timespan  = c("2003-2012", "2007-2016", "2011-2020"),
    geography = c("ByCounty", "Regional"),
    variant   = c("Hispanic", "NH-ByRace", "AllRaceEth")) %>% 
  mutate(
    txt_path = extdata_path(
      "UCD", 
      timespan,
      str_glue("UCD-{timespan}-SFBA-{geography}-{variant}.txt"))) 
```

```{r SFBA_UCD_data}
SFBA_UCD_data <-
  SFBA_UCD_metadata %>% 
  mutate(data = map(txt_path, import_WONDER_UCD)) %>% 
  #select(timespan, data) %>% 
  unnest(data) %>% 
  replace_na(list(cnty_name = "(average)", raceeth = "(all)"))
```

```{r fig_theme}
fig_theme <- 
  theme_simple() +
  theme_gridlines() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  theme_remove("axis", c("ticks", "line"), c("x", "y"))
```

```{r raceeth_colors}
raceeth_colors <-
  RACEETH_COLORS %>%          # from the `exptools` package
  rename(NatAm = NatAmer) 

raceeth_colors[["(all)"]] <- gray(0) # black
```

```{r fig_description}
fig_description <-
  labs(
    title = str_glue("Mortality Across the Nine-County Bay Area"),
    subtitle = "Age-adjusted all-cause rates, with 95% confidence intervals",
    caption = str_glue(
      "Accessed at http://wonder.cdc.gov/ucd-icd10.html on Sep 16, 2024 1:44:39 PM",
      str_draft(),
      .sep = "\n"))
```

```{r make_figure_by_raceeth}
make_figure_by_raceeth <- function (.data, ...) {
  
  timespan_levels <-
    with(.data, sort(unique(timespan)))
  
  timespan_shapes <-
    scale_shape_discrete()$palette(length(timespan_levels))
  
  ggplot(drop_units(.data), ...) +
    aes(x = cnty_name, 
        shape = factor(timespan, levels = timespan_levels),
        alpha = I(0.8),
        y = est(rate_adj), 
          color = raceeth,
          ymin = lower(rate_adj), 
          ymax = upper(rate_adj)) +
    geom_pointrange(
      aes(color = raceeth), 
      position = position_dodge(width = 0.2),
      data = ~ filter(., raceeth != "(all)")) + 
    scale_shape_manual(
      values = set_names(rev(timespan_shapes), timespan_levels)) +
    scale_x_discrete(
      name = NULL) +
    ggtools::scale_y_quantity(
      name = "Rate per 100,000",
      limits = c(0, 1200 / 100e3),
      labels = function (x) x * 100e3) +
    guides(
      shape = guide_legend(
        title = "Timespan",
        order = 1,
        override.aes = list(linewidth = 0))) +
    fig_description +
    fig_theme 
}
```

```{r fig1, fig.dim=c(8, 6), out.width=800, out.height=600}
SFBA_UCD_data %>% 
  filter(
    #cnty_name != "(all)",
    raceeth != "(all)") %>% 
  mutate(
    raceeth = fct_reorder(raceeth, -est(rate_adj)),
    cnty_name = fct_reorder(cnty_name, est(rate_adj)) %>% fct_relevel("(average)", after = 9)) %>% 
  make_figure_by_raceeth() +
  geom_vline(
    xintercept = 9.5) +
  aes(
    color = raceeth) + 
  scale_color_manual(
    values = raceeth_colors) +
  guides(
    color = guide_legend(
      title = "Race/Ethnicity",
      order = 2,
      override.aes = list(linewidth = 0))) 
```

```{r fig2, fig.dim=c(8, 6), out.width=800, out.height=600}
SFBA_UCD_data %>% 
  filter(
    timespan == "2011-2020") %>% 
  mutate(
    cnty_name = fct_reorder(cnty_name, est(rate_adj)) %>% fct_relevel("(average)", after = 9)) %>% 
  make_figure_by_raceeth() +
  geom_vline(
    xintercept = 9.5) +
  scale_color_manual(
    values = raceeth_colors) +
  geom_point( # CI is too small to matter; no need for `pointrange()`
    shape = 9,
    size = 2,
    data = ~ filter(., raceeth == "(all)")) +
  guides(
    color = guide_legend(
      title = "Race/Ethnicity",
      order = 2,
      override.aes = list(linewidth = 0))) 
```
